### PR TITLE
cleanup metadata codes

### LINKED ISSUE #12: Strezless Productionz Team
Experimenting a music career take off from scratch
any one with new ideas welcomed and will definitely be taken into consideration
Starring Artist known as Sin Estres 
Omar Orrantia

<iframe src="https://archive.org/embed/not-another-broken-heart" width="500" height="140" frameborder="0" webkitallowfullscreen="true" mozallowfullscreen="true" allowfullscreen></iframe

### PR DESCRIPTION
**Pull request by ghost**
Just trying to put in all codes from different sources to merge as Strezless Musick Productionz got content all over the web yet it is unorganized which makes it extremely difficult to administer a publishing business

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
Snapchat-1462127128
Not feeling too well, you can tell by staring at my face but I've approved this contribution to Strezless Musick Productionz (Music Publishing small business)
@`Sin Estres Orrantia`

**Comment by strezless** [comment]
Automate merging updates

**Review by StrezlessMusick — COMMENTED** [review]
Open repo

**Review by StrezlessMusick — COMMENTED** [review]
echo Hello 🌎 Welcome Strezless Musick 
name = input("What's your artist name?")
print(artist name = Sin Estres)

**Comment by StrezlessMusick** [comment]
[wiki/List_of_online_music_databases](https://en.m.wikipedia.org/wiki/List_of_online_music_databases#) 
@strezless

**Pull request closed without merging**
